# Simple Makefile for Triple Gaussian test
CXX = g++
ROOTFLAGS = $(shell root-config --cflags --libs)
CXXFLAGS = -std=c++11 -I. -g -O2

LIBDIR = build
LIBS = -L$(LIBDIR) -lLibRec
LDFLAGS = $(ROOTFLAGS) $(LIBS)

test_triple_gauss: test_triple_gauss.cpp
	$(CXX) $(CXXFLAGS) $< $(LDFLAGS) -o $@

clean:
	rm -f test_triple_gauss

.PHONY: clean
