// Author: Szymon Gamrat
// Date of last update: 26.05.2024

#ifndef FORT_COMMON_H
#define FORT_COMMON_H

#ifdef __cplusplus
extern "C"
{
#endif

  const Int_t NeleCluMax = 2000;
  const Int_t MaxNumClu = 100;
  const Int_t MaxNumVtx = 20;
  const Int_t MaxNumTrkV = 30;
  const Int_t MaxNumTrk = 100;
  const Int_t MaxNumDHSP = 1000;
  const Int_t nMaxDC = 1500;
  const Int_t NQihiMax = 1000;
  const Int_t NQcalMax = 32;
  const Int_t MaxNumFirstHit = 300;
  const Int_t MaxNtrkGen = 50;
  const Int_t MaxNvtxGen = 50;
  const Int_t TriggerElements = 300;

  //======================== Include constans.inc =========================
  const Float_t Mpip = 139.57039;
  const Float_t Mpio = 134.9768;
  const Float_t Mko = 497.611;
  const Float_t Momega = 782.66;
  const Float_t Cvel = 29.9792458;
  const Float_t TauKs = 0.08954;
  const Float_t Mphi = 1019.461;
  //========================= Include klspm00.cin =========================
  const Int_t NCLMIN = 4;
  const Float_t ECLMIN = 20.;
  const Float_t vtxdist = 500.;
  const Int_t testcounter = 100;
  const Int_t MaxNumFitPar = 38;
  const Int_t MaxNumConstr = 10;
  const Int_t MaxNumComega = 8;
  const Int_t cutN = 6;
  const Int_t errN = 17;

  const Int_t MaxNumOverlapStream = 8;
  const Int_t MaxNumCLINF = 100;
  const Int_t NTCLOMax = 40;

  extern struct
  {
    Int_t nev;
    Int_t pileup;
    Int_t gcod;
    Int_t phid;
    Int_t a1typ;
    Int_t a2typ;
    Int_t a3typ;
    Int_t b1typ;
    Int_t b2typ;
    Int_t b3typ;
    Int_t nrundata;
    Float_t tphased_mc;
    Float_t t0dc0;
    Float_t t0hit0;
    Float_t t0clu0;
    Float_t T0step1;
    Float_t DelayCable;
    Float_t Tbunch;
    Int_t TimeSec;
    Int_t TimeMusec;
    Int_t mcflag;
    Float_t Bpx;
    Float_t Bpy;
    Float_t Bpz;
    Float_t Bx;
    Float_t By;
    Float_t Bz;
    Float_t Bwidpx;
    Float_t Bwidpy;
    Float_t Bwidpz;
    Float_t Bsx;
    Float_t Bsy;
    Float_t Bsz;
    Float_t Blumx;
    Float_t Blumz;
    Float_t Broots;
    Float_t BrootsErr;
    Int_t necls2;
    Int_t ECLtrgw2;
    Int_t ECLfilfo2;
    Int_t ECLword2[MaxNumOverlapStream];
    Int_t ECLstream2[MaxNumOverlapStream];
    Int_t ECLtagnum2[MaxNumOverlapStream];
    Int_t ECLevtype2[MaxNumOverlapStream];
    Int_t nclu;
    Float_t EneCl[MaxNumClu];
    Float_t TclOld[MaxNumClu];
    Float_t Xcl[MaxNumClu];
    Float_t Ycl[MaxNumClu];
    Float_t Zcl[MaxNumClu];
    Float_t Xacl[MaxNumClu];
    Float_t Yacl[MaxNumClu];
    Float_t Zacl[MaxNumClu];
    Float_t XRmCl[MaxNumClu];
    Float_t YRmsCl[MaxNumClu];
    Float_t ZrmsCl[MaxNumClu];
    Float_t TrmsCl[MaxNumClu];
    Int_t FlagCl[MaxNumClu];
    Int_t nclumc;
    Int_t Npar[MaxNumClu];
    Int_t Pnum1[MaxNumClu];
    Int_t Pid1[MaxNumClu];
    Int_t Pnum2[MaxNumClu];
    Int_t Pid2[MaxNumClu];
    Int_t Pnum3[MaxNumClu];
    Int_t Pid3[MaxNumClu];
    Int_t ntv;
    Int_t ivOld[MaxNumTrkV];
    Int_t trknumv[MaxNumTrkV];
    Float_t CurV[MaxNumTrkV];
    Float_t PhiV[MaxNumTrkV];
    Float_t CotV[MaxNumTrkV];
    Float_t PxTV[MaxNumTrkV];
    Float_t PyTV[MaxNumTrkV];
    Float_t PzTV[MaxNumTrkV];
    Int_t nv;
    Int_t vtx[MaxNumVtx];
    Float_t xvOld[MaxNumVtx];
    Float_t yvOld[MaxNumVtx];
    Float_t zvOld[MaxNumVtx];
    Float_t chivtx[MaxNumVtx];
    Int_t qualv[MaxNumVtx];
    Int_t fitidv[MaxNumVtx];
    Float_t VTXcov1[MaxNumVtx];
    Float_t VTXcov2[MaxNumVtx];
    Float_t VTXcov3[MaxNumVtx];
    Float_t VTXcov4[MaxNumVtx];
    Float_t VTXcov5[MaxNumVtx];
    Float_t VTXcov6[MaxNumVtx];
    Int_t nt;
    Int_t trkind[MaxNumTrk];
    Float_t chi2fit[MaxNumTrk];
    Float_t chi2ms[MaxNumTrk];
    Int_t ntfmc;
    Int_t trkine1[MaxNumTrk];
    Int_t trtype1[MaxNumTrk];
    Int_t trhits1[MaxNumTrk];
    Int_t trkine2[MaxNumTrk];
    Int_t trtype2[MaxNumTrk];
    Int_t trhits2[MaxNumTrk];
    Int_t trkine3[MaxNumTrk];
    Int_t trtype3[MaxNumTrk];
    Int_t trhits3[MaxNumTrk];
    Int_t ntmc;
    Int_t kine[MaxNtrkGen];
    Int_t pidmcOld[MaxNtrkGen];
    Int_t virmom[MaxNtrkGen];
    Float_t pxmc[MaxNtrkGen];
    Float_t pymc[MaxNtrkGen];
    Float_t pzmc[MaxNtrkGen];
    Float_t themc[MaxNtrkGen];
    Float_t phimc[MaxNtrkGen];
    Int_t vtxmcOld[MaxNtrkGen];
    Int_t nvtxmc;
    Int_t kinmom[MaxNvtxGen];
    Int_t motherOld[MaxNvtxGen];
    Float_t xvmc[MaxNvtxGen];
    Float_t yvmc[MaxNvtxGen];
    Float_t zvmc[MaxNvtxGen];
    Float_t ntvtx[MaxNvtxGen];
    Int_t ntcl;
    Int_t Asstr[NTCLOMax];
    Int_t Asscl[NTCLOMax];
    Int_t verver[NTCLOMax];
    Float_t xext[NTCLOMax];
    Float_t yext[NTCLOMax];
    Float_t zext[NTCLOMax];
    Float_t Assleng[NTCLOMax];
    Float_t AssChi[NTCLOMax];
    Float_t extPx[NTCLOMax];
    Float_t extPy[NTCLOMax];
    Float_t extPz[NTCLOMax];
    Int_t ncli2;
    Int_t ECLOword2[MaxNumCLINF];
    Int_t idpart2[MaxNumCLINF];
    Int_t dtclpo2[MaxNumCLINF];
    Int_t dvvnpo2[MaxNumCLINF];
    Int_t stre2[MaxNumCLINF];
    Int_t algo2[MaxNumCLINF];
    Float_t KchMC[9];
    Float_t KneMC[9];
    Float_t KchRec[9];
    Float_t KchRecKS[9];
    Float_t KchRecKL[9];
    Float_t KchRecClose[9];
    Float_t KneRec[9];
    Float_t KchBoost[9];
    Float_t ip[3];
    Float_t ip_closest[3];
    Float_t ip_plane[3];
    Float_t ipmcOld[3];
    Int_t vtaken[3];
    Int_t vtakenks[3];
    Int_t vtakenkl[3];
    Int_t vtakenclose[3];
    Int_t mcISR;
    Int_t mctruth;
    Int_t ncl;
    Int_t ncll[MaxNumClu];
    Int_t nclwrong;
    Int_t ncllwrong[MaxNumClu];
    Float_t DlMC;
    Float_t DtMC;
    Float_t DlBoostLor;
    Float_t DtBoostLor;
    Float_t DlTriangle;
    Float_t DtTriangle;
    Float_t DlTrilateration;
    Float_t DtTrilateration;
    Float_t DlBoostRec;
    Float_t DtBoostRec;
    Float_t DlRec;
    Float_t DtRec;
    Float_t cldist;
    Float_t KneRecLor[9];
    Float_t KneRecLorFit[9];
    Float_t KneRecTriangle[10];
    Float_t KneRecTrilateration[10];
    Float_t pi0[2];
    Float_t minv4gam;
    Float_t Rc;
    Float_t Rtc;
    Float_t Rn;
    Float_t Rtn;
    Float_t RcMC;
    Float_t RtcMC;
    Float_t RnMC;
    Float_t RtnMC;
    Float_t ominv[2];
    Float_t chdist;
    Float_t trc[MaxNumClu];
    Float_t trcFit[MaxNumClu];
    Float_t trcv[MaxNumClu];
    Float_t trcvFit[MaxNumClu];
    Int_t ErrId;
    Int_t ErrFlag[errN];
    Int_t CutId;
    Int_t g4taken[4];
    Int_t g4takenFit[4];
    Float_t g4vtxerr[3];
    Float_t g4vtxerrFit[3];
    Float_t KchFit[9];
    Float_t KneFit[9];
    Float_t chdistFit;
    Float_t cldistFit;
    Float_t ipFit[3];
    Int_t nclwrongFit;
    Int_t ncllwrongFit[MaxNumClu];
    Float_t DlFit;
    Float_t DtFit;
    Float_t RcFit;
    Float_t RtcFit;
    Float_t RnFit;
    Float_t RtnFit;
    Float_t pi0Fit[2];
    Float_t minv4gamFit;
    Float_t ominvFit[2];
    Float_t Chi2;
    Float_t Chi2_w;
    Int_t Niter;
    Int_t Niter_w;
    Float_t FitPar[MaxNumFitPar];
    Float_t ErrPar[MaxNumFitPar];
    Float_t BkgFitPar[MaxNumFitPar];
    Float_t BkgErrPar[MaxNumFitPar];
    Float_t FitParStart[MaxNumFitPar];
    Float_t ErrParStart[MaxNumFitPar];
    Float_t PpioOmega[4];
    Float_t PpioOmegaFit[4];
    Float_t P4PriRest[4];
    Float_t P4PriRestFit[4];
    Float_t trk1[4];
    Float_t trk2[4];
    Float_t trk1KS[4];
    Float_t trk2KS[4];
    Float_t trk1KL[4];
    Float_t trk2KL[4];
    Float_t trk1Close[4];
    Float_t trk2Close[4];
    Float_t cosTrk;
    Float_t cosTrkKS;
    Float_t cosTrkKL;
    Float_t cosTrkClose;
    Float_t cosTrkCM;
    Float_t Qmiss;
    Int_t Nconstr;
    Int_t Nconstr_w;
    Int_t nparfit;
    Int_t gpairtaken[2];
    Int_t gpairtakenFit[2];
    Float_t PgamRec1fit[4];
    Float_t PgamRec2fit[4];
    Float_t PgamRec3fit[4];
    Float_t PgamRec4fit[4];
    Float_t PgamRec1[4];
    Float_t PgamRec2[4];
    Float_t PgamRec3[4];
    Float_t PgamRec4[4];
    Int_t ChVtxId;
    Float_t Trkk1[3];
    Float_t Trkk2[3];
    Float_t ChaVtx[3];
    Float_t NeuVtx[3];
    Float_t PhiVtx[3];
    Float_t TrkIdx[2];
    Int_t CluIdx[4];
    Int_t simok;
    Float_t test[testcounter];
    Int_t vtx_with_two_tracks;
    Int_t done4;
  } interfcommon_;

#ifdef __cplusplus
}
#endif

#endif // !FORT_COMMON_H