// Author: Szymon Gamrat
// Date of last update: 26.05.2024

#ifndef FORT_COMMON_H
#define FORT_COMMON_H

#include <const.h>

#ifdef __cplusplus
extern "C"
{
#endif

  const int NeleCluMax = 2000;
  const int MaxNumClu = 100;
  const int MaxNumVtx = 20;
  const int MaxNumTrkV = 30;
  const int MaxNumTrk = 100;
  const int MaxNumDHSP = 1000;
  const int nMaxDC = 1500;
  const int NQihiMax = 1000;
  const int NQcalMax = 32;
  const int MaxNumFirstHit = 300;
  const int MaxNtrkGen = 50;
  const int MaxNvtxGen = 50;
  const int TriggerElements = 300;

  //======================== Include constans.inc =========================
  const double Mpip = 139.57039;
  const double Mpio = 134.9768;
  const double Mko = mK0;
  const double Momega = 782.66;
  const double Cvel = 29.9792458;
  const double TauKs = 0.08954;
  const double Mphi = 1019.461;
  //========================= Include klspm00.cin =========================
  const int NCLMIN = 4;
  const double ECLMIN = 20.;
  const double vtxdist = 500.;
  const int testcounter = 100;
  const int MaxNumFitPar = 38;
  const int MaxNumConstr = 10;
  const int MaxNumComega = 8;
  const int cutN = 6;
  const int errN = 17;

  const int MaxNumOverlapStream = 8;
  const int MaxNumCLINF = 100;
  const int NTCLOMax = 40;

  extern struct
  {
    int nev;
    int pileup;
    int gcod;
    int phid;
    int a1typ;
    int a2typ;
    int a3typ;
    int b1typ;
    int b2typ;
    int b3typ;
    int nrundata;
    double tphased_mc;
    double t0dc0;
    double t0hit0;
    double t0clu0;
    double T0step1;
    double DelayCable;
    double Tbunch;
    int TimeSec;
    int TimeMusec;
    int mcflag;
    double Bpx;
    double Bpy;
    double Bpz;
    double Bx;
    double By;
    double Bz;
    double Bwidpx;
    double Bwidpy;
    double Bwidpz;
    double Bsx;
    double Bsy;
    double Bsz;
    double Blumx;
    double Blumz;
    double Broots;
    double BrootsErr;
    int necls2;
    int ECLtrgw2;
    int ECLfilfo2;
    int ECLword2[MaxNumOverlapStream];
    int ECLstream2[MaxNumOverlapStream];
    int ECLtagnum2[MaxNumOverlapStream];
    int ECLevtype2[MaxNumOverlapStream];
    int nclu;
    double EneCl[MaxNumClu];
    double TclOld[MaxNumClu];
    double Xcl[MaxNumClu];
    double Ycl[MaxNumClu];
    double Zcl[MaxNumClu];
    double Xacl[MaxNumClu];
    double Yacl[MaxNumClu];
    double Zacl[MaxNumClu];
    double XRmCl[MaxNumClu];
    double YRmsCl[MaxNumClu];
    double ZrmsCl[MaxNumClu];
    double TrmsCl[MaxNumClu];
    int FlagCl[MaxNumClu];
    int nclumc;
    int Npar[MaxNumClu];
    int Pnum1[MaxNumClu];
    int Pid1[MaxNumClu];
    int Pnum2[MaxNumClu];
    int Pid2[MaxNumClu];
    int Pnum3[MaxNumClu];
    int Pid3[MaxNumClu];
    int ntv;
    int ivOld[MaxNumTrkV];
    int trknumv[MaxNumTrkV];
    double CurV[MaxNumTrkV];
    double PhiV[MaxNumTrkV];
    double CotV[MaxNumTrkV];
    double PxTV[MaxNumTrkV];
    double PyTV[MaxNumTrkV];
    double PzTV[MaxNumTrkV];
    int nv;
    int vtx[MaxNumVtx];
    double xvOld[MaxNumVtx];
    double yvOld[MaxNumVtx];
    double zvOld[MaxNumVtx];
    double chivtx[MaxNumVtx];
    int qualv[MaxNumVtx];
    int fitidv[MaxNumVtx];
    double VTXcov1[MaxNumVtx];
    double VTXcov2[MaxNumVtx];
    double VTXcov3[MaxNumVtx];
    double VTXcov4[MaxNumVtx];
    double VTXcov5[MaxNumVtx];
    double VTXcov6[MaxNumVtx];
    int nt;
    int trkind[MaxNumTrk];
    double chi2fit[MaxNumTrk];
    double chi2ms[MaxNumTrk];
    int ntfmc;
    int trkine1[MaxNumTrk];
    int trtype1[MaxNumTrk];
    int trhits1[MaxNumTrk];
    int trkine2[MaxNumTrk];
    int trtype2[MaxNumTrk];
    int trhits2[MaxNumTrk];
    int trkine3[MaxNumTrk];
    int trtype3[MaxNumTrk];
    int trhits3[MaxNumTrk];
    int ntmc;
    int kine[MaxNtrkGen];
    int pidmcOld[MaxNtrkGen];
    int virmom[MaxNtrkGen];
    double pxmc[MaxNtrkGen];
    double pymc[MaxNtrkGen];
    double pzmc[MaxNtrkGen];
    double themc[MaxNtrkGen];
    double phimc[MaxNtrkGen];
    int vtxmcOld[MaxNtrkGen];
    int nvtxmc;
    int kinmom[MaxNvtxGen];
    int motherOld[MaxNvtxGen];
    double xvmc[MaxNvtxGen];
    double yvmc[MaxNvtxGen];
    double zvmc[MaxNvtxGen];
    double ntvtx[MaxNvtxGen];
    int ntcl;
    int Asstr[NTCLOMax];
    int Asscl[NTCLOMax];
    int verver[NTCLOMax];
    double xext[NTCLOMax];
    double yext[NTCLOMax];
    double zext[NTCLOMax];
    double Assleng[NTCLOMax];
    double AssChi[NTCLOMax];
    double extPx[NTCLOMax];
    double extPy[NTCLOMax];
    double extPz[NTCLOMax];
    int ncli2;
    int ECLOword2[MaxNumCLINF];
    int idpart2[MaxNumCLINF];
    int dtclpo2[MaxNumCLINF];
    int dvvnpo2[MaxNumCLINF];
    int stre2[MaxNumCLINF];
    int algo2[MaxNumCLINF];
    double KchMC[9];
    double KneMC[9];
    double KchRec[9];
    double KchRecKS[9];
    double KchRecKL[9];
    double KchRecClose[9];
    double KneRec[9];
    double KchBoost[9];
    double ip[3];
    double ip_closest[3];
    double ip_plane[3];
    double ipmcOld[3];
    int vtaken[3];
    int vtakenks[3];
    int vtakenkl[3];
    int vtakenclose[3];
    int mcISR;
    int mctruth;
    int ncl;
    int ncll[MaxNumClu];
    int nclwrong;
    int ncllwrong[MaxNumClu];
    double DlMC;
    double DtMC;
    double DlBoostLor;
    double DtBoostLor;
    double DlBoostRec;
    double DtBoostRec;
    double DlRec;
    double DtRec;
    double cldist;
    double KneRecLor[9];
    double KneRecLorFit[9];
    double pi0[2];
    double minv4gam;
    double Rc;
    double Rtc;
    double Rn;
    double Rtn;
    double RcMC;
    double RtcMC;
    double RnMC;
    double RtnMC;
    double ominv[2];
    double chdist;
    double trc[MaxNumClu];
    double trcFit[MaxNumClu];
    double trcv[MaxNumClu];
    double trcvFit[MaxNumClu];
    int ErrId;
    int CutId;
    int g4taken[4];
    int g4takenFit[4];
    double g4vtxerr[3];
    double g4vtxerrFit[3];
    double KchFit[9];
    double KneFit[9];
    double chdistFit;
    double cldistFit;
    double ipFit[3];
    int nclwrongFit;
    int ncllwrongFit[MaxNumClu];
    double DlFit;
    double DtFit;
    double RcFit;
    double RtcFit;
    double RnFit;
    double RtnFit;
    double pi0Fit[2];
    double minv4gamFit;
    double ominvFit[2];
    double Chi2;
    double Chi2_w;
    int Niter;
    int Niter_w;
    double FitPar[MaxNumFitPar];
    double ErrPar[MaxNumFitPar];
    double BkgFitPar[MaxNumFitPar];
    double BkgErrPar[MaxNumFitPar];
    double FitParStart[MaxNumFitPar];
    double ErrParStart[MaxNumFitPar];
    double PpioOmega[4];
    double PpioOmegaFit[4];
    double P4PriRest[4];
    double P4PriRestFit[4];
    double trk1[4];
    double trk2[4];
    double trk1KS[4];
    double trk2KS[4];
    double trk1KL[4];
    double trk2KL[4];
    double trk1Close[4];
    double trk2Close[4];
    double cosTrk;
    double cosTrkKS;
    double cosTrkKL;
    double cosTrkClose;
    double cosTrkCM;
    double Qmiss;
    int Nconstr;
    int Nconstr_w;
    int nparfit;
    int gpairtaken[2];
    int gpairtakenFit[2];
    double PgamRec1fit[4];
    double PgamRec2fit[4];
    double PgamRec3fit[4];
    double PgamRec4fit[4];
    double PgamRec1[4];
    double PgamRec2[4];
    double PgamRec3[4];
    double PgamRec4[4];
    int ChVtxId;
    double Trkk1[3];
    double Trkk2[3];
    double ChaVtx[3];
    double NeuVtx[3];
    double PhiVtx[3];
    double TrkIdx[2];
    int CluIdx[4];
    int simok;
    double test[testcounter];
    int vtx_with_two_tracks;
  } interfcommon_;

#ifdef __cplusplus
}
#endif

#endif // !FORT_COMMON_H