#pragma once

namespace KLOE
{
  enum class SelectionCode {
    NONE = 0,
    FINAL_SIGNAL = 1,
    THREE_PI0_CONTROL_SAMPLE_TAG = 2,
    SEMILEPTONIC_CONTROL_SAMPLE_TAG = 3,
    DOUBLE_PINE_CONTROL_SAMPLE_TAG = 4,
    DOUBLE_PINE_CONTROL_SAMPLE_SIGNAL_FINAL_AFTER_TAG = 5,
    DOUBLE_PICH_KS_CONTROL_SAMPLE_TAG = 6,
    DOUBLE_PICH_KS_CONTROL_SAMPLE_SIGNAL_FINAL_AFTER_TAG = 7,
    DOUBLE_PICH_KL_CONTROL_SAMPLE_TAG = 8,
    DOUBLE_PICH_KL_CONTROL_SAMPLE_SIGNAL_FINAL_AFTER_TAG = 9,

    CUSTOM_SELECTION = 10,

    INVALID = 11
  };
}